version: '3'
services:
  smava-nginx:
    build: nginx/.
    image: smava-nginx
    depends_on:
      - smava-web
    ports:
      - "80:80"

  smava-web:
    build: .
    image: smava-web
    container_name: smava-web
    ports:
      - "8080:8080"
